version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: tunturuntun/yamdb:latest
    volumes:
      - .code/var/html/static:/code/var/html/static 
      - .code/var/html/media:/code/var/html/media
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:alpine 
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .code/var/html/static:/code/var/html/static
      - .code/var/html/media:/code/var/html/media
    expose:
      - 8000 
    ports:
      - 8080:80
    depends_on:
      - web

