version: '3.8'

volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: tunturuntun/yamdb:latest
    volumes:
      - static:/code/var/html/static
    restart: always
    expose:
      - 8000 
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - static:/code/var/html/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - web

