version: '3.8'

volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: tunturuntun/yamdb:v1
    volumes:
      - ./static:/code/static
    restart: always
    expose:
      - 8000 
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - ./static:/static
    ports:
      - 1337:80
    depends_on:
      - web

